id: A9C50DEE1
title: Uddāna 2
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 22:15:27.172700
  last_modified_at: 2022-03-01 22:15:27.172707
