id: A9C50DEE1
title: UddÄna 1
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 22:15:27.121539
  last_modified_at: 2022-03-01 22:15:27.121546
